serve:
  browser: false
  hostname: localhost

sources:
  - name: Sushi
    handler:
      graphql:
        endpoint: https://gateway-arbitrum.network.thegraph.com/api/8e6ea7d66fc14ceaf967a103a1da00d7/subgraphs/id/HUZDsRpEVP2AvzDCyzDHtdc64dyDxx8FQjzsmqSg4H3B
