name: Audits

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  javascript:
    uses: ./.github/workflows/reusable-audit-javascript.yml
    strategy:
      matrix:
        workspace:
          - express-graphql
          - apollo-server
          - mercurius
          - graphql-yoga
          - graphql-helix
          - graph-client
    with:
      workspace: ${{ matrix.workspace }}
  docker:
    uses: ./.github/workflows/reusable-audit-docker.yml
    strategy:
      matrix:
        workspace:
          - hotchocolate
          - postgraphile
          - pioneer
          - deno
    with:
      workspace: ${{ matrix.workspace }}
  url:
    uses: ./.github/workflows/reusable-audit-url.yml
    strategy:
      matrix:
        workspace:
          - name: thegraph
            url: https://api.thegraph.com/subgraphs/name/sushiswap/exchange/graphql
    with:
      workspace: ${{ matrix.workspace.name }}
      url: ${{ matrix.workspace.url }}

  report:
    name: Report
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    needs: [javascript, docker, url]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref || github.ref_name }}
      - name: Download audit reports
        uses: actions/download-artifact@v3
        with:
          name: audit-reports
      - name: Diff
        run: git diff --minimal
      - name: Commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          [ -z "$(git status --porcelain)" ] \
            && echo "::notice::Nothing new to report." \
            || (git add . && git commit -m "docs(implementations): audit report [skip ci]" && git push)
