name: Audits

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  express-graphql:
    uses: ./.github/workflows/reusable-audit-javascript.yml
    with:
      workspace: express-graphql
  apollo-server:
    uses: ./.github/workflows/reusable-audit-javascript.yml
    with:
      workspace: apollo-server
  mercurius:
    uses: ./.github/workflows/reusable-audit-javascript.yml
    with:
      workspace: mercurius
  graphql-yoga:
    uses: ./.github/workflows/reusable-audit-javascript.yml
    with:
      workspace: graphql-yoga
  graphql-helix:
    uses: ./.github/workflows/reusable-audit-javascript.yml
    with:
      workspace: graphql-helix
  graph-client:
    uses: ./.github/workflows/reusable-audit-javascript.yml
    with:
      workspace: graph-client
  thegraph:
    uses: ./.github/workflows/reusable-audit-url.yml
    with:
      workspace: thegraph
      url: https://api.thegraph.com/subgraphs/name/sushiswap/exchange/graphql
  hotchocolate:
    uses: ./.github/workflows/reusable-audit-docker.yml
    with:
      workspace: hotchocolate
  postgraphile:
    uses: ./.github/workflows/reusable-audit-docker.yml
    with:
      workspace: postgraphile
  pioneer:
    uses: ./.github/workflows/reusable-audit-docker.yml
    with:
      workspace: pioneer
  deno:
    uses: ./.github/workflows/reusable-audit-docker.yml
    with:
      workspace: deno

  report:
    name: Report
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    needs:
      [
        express-graphql,
        apollo-server,
        mercurius,
        graphql-yoga,
        graphql-helix,
        graph-client,
        thegraph,
        hotchocolate,
        postgraphile,
        pioneer,
        deno,
      ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref || github.ref_name }}
      - name: Download audit reports
        uses: actions/download-artifact@v3
        with:
          name: audit-reports
      - name: Diff
        run: git diff --minimal
      - name: Commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          [ -z "$(git status --porcelain)" ] \
            && echo "::notice::Nothing new to report." \
            || (git add . && git commit -m "docs(implementations): audit report [skip ci]" && git push)
