name: Audits

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - master

jobs:
  express-graphql:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    env:
      PORT: 4000
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - name: Install
        run: yarn install --immutable
      - name: Build
        run: yarn build:esm
      - name: Start
        run: yarn workspace express-graphql start &
      - name: Audit
        run: node scripts/audit-implementation.mjs README.md
      - name: Upload report
        uses: actions/upload-artifact@v3
        with:
          name: express-graphql-report
          path: README.md

  apollo-server:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    env:
      PORT: 4000
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - name: Install
        run: yarn install --immutable
      - name: Build
        run: yarn build:esm
      - name: Start
        run: yarn workspace apollo-server start &
      - name: Audit
        run: node scripts/audit-implementation.mjs README.md
      - name: Upload report
        uses: actions/upload-artifact@v3
        with:
          name: apollo-server-report
          path: README.md

  mercurius:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    env:
      PORT: 4000
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - name: Install
        run: yarn install --immutable
      - name: Build
        run: yarn build:esm
      - name: Start
        run: yarn workspace mercurius start &
      - name: Audit
        run: node scripts/audit-implementation.mjs README.md
      - name: Upload report
        uses: actions/upload-artifact@v3
        with:
          name: mercurius-report
          path: README.md

  graphql-yoga:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    env:
      PORT: 4000
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - name: Install
        run: yarn install --immutable
      - name: Build
        run: yarn build:esm
      - name: Start
        run: yarn workspace graphql-yoga start &
      - name: Audit
        run: node scripts/audit-implementation.mjs README.md
      - name: Upload report
        uses: actions/upload-artifact@v3
        with:
          name: graphql-yoga-report
          path: README.md

  graphql-helix:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    env:
      PORT: 4000
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - name: Install
        run: yarn install --immutable
      - name: Build
        run: yarn build:esm
      - name: Start
        run: yarn workspace graphql-helix start &
      - name: Audit
        run: node scripts/audit-implementation.mjs README.md
      - name: Upload report
        uses: actions/upload-artifact@v3
        with:
          name: graphql-helix-report
          path: README.md

  graph-client:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    env:
      PORT: 4000
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - name: Install
        run: yarn install --immutable
      - name: Build
        run: yarn build:esm
      - name: Start
        run: yarn workspace graph-client start &
      - name: Audit
        run: node scripts/audit-implementation.mjs README.md
      - name: Upload report
        uses: actions/upload-artifact@v3
        with:
          name: graph-client-report
          path: README.md

  thegraph:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    env:
      URL: https://api.thegraph.com/subgraphs/name/sushiswap/exchange/graphql
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - name: Install
        run: yarn install --immutable
      - name: Build
        run: yarn build:esm
      - name: Audit
        run: node scripts/audit-implementation.mjs README.md
      - name: Upload report
        uses: actions/upload-artifact@v3
        with:
          name: thegraph-report
          path: README.md

  hotchocolate:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    env:
      PORT: 4000
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - name: Install
        run: yarn install --immutable
      - name: Build
        run: yarn build:esm
      - name: Start
        run: yarn workspace hotchocolate start -d --wait
      # TODO: cache docker build artifacts
      - name: Audit
        run: node scripts/audit-implementation.mjs README.md
      - name: Upload report
        uses: actions/upload-artifact@v3
        with:
          name: hotchocolate-report
          path: README.md

  report:
    name: Report
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    needs:
      [
        express-graphql,
        apollo-server,
        mercurius,
        graphql-yoga,
        graphql-helix,
        graph-client,
        thegraph,
        hotchocolate,
      ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref || github.ref_name }}
      - name: Download express-graphql report
        uses: actions/download-artifact@v3
        with:
          name: express-graphql-report
          path: implementations/express-graphql
      - name: Download apollo-server report
        uses: actions/download-artifact@v3
        with:
          name: 'apollo-server-report'
          path: implementations/apollo-server
      - name: Download mercurius report
        uses: actions/download-artifact@v3
        with:
          name: mercurius-report
          path: implementations/mercurius
      - name: Download graphql-yoga report
        uses: actions/download-artifact@v3
        with:
          name: graphql-yoga-report
          path: implementations/graphql-yoga
      - name: Download graphql-helix report
        uses: actions/download-artifact@v3
        with:
          name: graphql-helix-report
          path: implementations/graphql-helix
      - name: Download graph-client report
        uses: actions/download-artifact@v3
        with:
          name: graph-client-report
          path: implementations/graph-client
      - name: Download thegraph report
        uses: actions/download-artifact@v3
        with:
          name: thegraph-report
          path: implementations/thegraph
      - name: Download hotchocolate report
        uses: actions/download-artifact@v3
        with:
          name: hotchocolate-report
          path: implementations/hotchocolate
      - name: Commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          [ -z "$(git status --porcelain)" ] \
            && echo "::notice::Nothing new to report." \
            || (git add . && git commit -m "docs(implementations): audit report [skip ci]" && git push)
