name: Audits

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - master

jobs:
  express-graphql:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    env:
      PORT: 4000
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: 'yarn'
      - name: Install
        run: yarn install --immutable
      - name: Build
        run: yarn build:esm
      - name: Start
        run: node implementations/express-graphql &
      - name: Audit
        run: node scripts/audit-implementation.mjs implementations/express-graphql/README.md
      - name: Commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -am "docs(express-graphql): audit report [skip ci]"
          git push

  apollo-server:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    env:
      PORT: 4000
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: 'yarn'
      - name: Install
        run: yarn install --immutable
      - name: Build
        run: yarn build:esm
      - name: Start
        run: node implementations/apollo-server &
      - name: Audit
        run: node scripts/audit-implementation.mjs implementations/apollo-server/README.md
      - name: Commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -am "docs(apollo-server): audit report [skip ci]"
          git push

  mercurius:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    env:
      PORT: 4000
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: 'yarn'
      - name: Install
        run: yarn install --immutable
      - name: Build
        run: yarn build:esm
      - name: Start
        run: node implementations/mercurius &
      - name: Audit
        run: node scripts/audit-implementation.mjs implementations/mercurius/README.md
      - name: Commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -am "docs(mercurius): audit report [skip ci]"
          git push

  graphql-yoga:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    env:
      PORT: 4000
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: 'yarn'
      - name: Install
        run: yarn install --immutable
      - name: Build
        run: yarn build:esm
      - name: Start
        run: node implementations/graphql-yoga &
      - name: Audit
        run: node scripts/audit-implementation.mjs implementations/graphql-yoga/README.md
      - name: Commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -am "docs(graphql-yoga): audit report [skip ci]"
          git push

  graphql-helix:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    env:
      PORT: 4000
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: 'yarn'
      - name: Install
        run: yarn install --immutable
      - name: Build
        run: yarn build:esm
      - name: Start
        run: node implementations/graphql-helix &
      - name: Audit
        run: node scripts/audit-implementation.mjs implementations/graphql-helix/README.md
      - name: Commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "docs(graphql-helix): audit report [skip ci]"
          git push
