name: Benchmark

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

env:
  K6_VERSION: v0.44.1
  PORT: 50000

jobs:
  http:
    name: http
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - name: Install
        run: yarn install --immutable
      - name: Download k6
        run: |
          curl https://github.com/grafana/k6/releases/download/${{ env.K6_VERSION }}/k6-${{ env.K6_VERSION }}-linux-amd64.tar.gz -L | tar xvz --strip-components 1
      - name: Build
        run: yarn run build:esm
      - name: Run
        run: node benchmark/servers/http.mjs &
      - name: Benchmark
        run: ./k6 run benchmark/k6.mjs --summary-export summary.json
      - name: Summary
        run: |
          echo '```json' >> $GITHUB_STEP_SUMMARY
          cat summary.json >> $GITHUB_STEP_SUMMARY
          echo -e '\n```' >> $GITHUB_STEP_SUMMARY

  express:
    name: express
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - name: Install
        run: yarn install --immutable
      - name: Download k6
        run: |
          curl https://github.com/grafana/k6/releases/download/${{ env.K6_VERSION }}/k6-${{ env.K6_VERSION }}-linux-amd64.tar.gz -L | tar xvz --strip-components 1
      - name: Build
        run: yarn run build:esm
      - name: Run
        run: node benchmark/servers/express.mjs &
      - name: Benchmark
        run: ./k6 run benchmark/k6.mjs --summary-export summary.json
      - name: Summary
        run: |
          echo '```json' >> $GITHUB_STEP_SUMMARY
          cat summary.json >> $GITHUB_STEP_SUMMARY
          echo -e '\n```' >> $GITHUB_STEP_SUMMARY

  fastify:
    name: fastify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - name: Install
        run: yarn install --immutable
      - name: Download k6
        run: |
          curl https://github.com/grafana/k6/releases/download/${{ env.K6_VERSION }}/k6-${{ env.K6_VERSION }}-linux-amd64.tar.gz -L | tar xvz --strip-components 1
      - name: Build
        run: yarn run build:esm
      - name: Run
        run: node benchmark/servers/fastify.mjs &
      - name: Benchmark
        run: ./k6 run benchmark/k6.mjs --summary-export summary.json
      - name: Summary
        run: |
          echo '```json' >> $GITHUB_STEP_SUMMARY
          cat summary.json >> $GITHUB_STEP_SUMMARY
          echo -e '\n```' >> $GITHUB_STEP_SUMMARY

  bun:
    name: bun
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - name: Set up bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install
        run: yarn install --immutable
      - name: Download k6
        run: |
          curl https://github.com/grafana/k6/releases/download/${{ env.K6_VERSION }}/k6-${{ env.K6_VERSION }}-linux-amd64.tar.gz -L | tar xvz --strip-components 1
      - name: Build
        run: yarn run build:esm
      - name: Run
        run: bun run benchmark/servers/bun.mjs &
      - name: Benchmark
        run: ./k6 run benchmark/k6.mjs --summary-export summary.json
      - name: Summary
        run: |
          echo '```json' >> $GITHUB_STEP_SUMMARY
          cat summary.json >> $GITHUB_STEP_SUMMARY
          echo -e '\n```' >> $GITHUB_STEP_SUMMARY
