name: Reusable audit JavaScript

on:
  workflow_call:
    inputs:
      workspace:
        required: true
        type: string

jobs:
  audit:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    env:
      PORT: 4000
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - name: Install
        run: yarn install --immutable
      - name: Build
        run: yarn build:esm
      - name: Start
        run: yarn workspace ${{ inputs.workspace }} start &
      - name: Audit
        run: node scripts/audit-implementation.mjs implementations/${{ inputs.workspace }}
      - name: Upload audit report
        uses: actions/upload-artifact@v3
        with:
          name: audit-reports
          path: |
            implementations/${{ inputs.workspace }}/README.md
            implementations/${{ inputs.workspace }}/report.json
